apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    url: timescaledb:5432
    user: risk_user
    secureJsonData:
      password: risk_pass
    jsonData:
      database: risk_monitor
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true